### ISSUE TITLE
Данные не инкапсулированы

### ISSUE THREAD

**Issue by dev-pro-alexander-subota** [antlelik/propertyCross#1]
Сущность приложения (обьект `propertyCross`) обьявлена литерально. Данные не инкапсулированы.
Переписать используя паттерны проектирования JS модулей.
Хорошая книжка по паттернам [здесь](https://addyosmani.com/resources/essentialjsdesignpatterns/book/).

**Comment by antlelik** [comment]
перевел в функцию, инкапсулировал

**Comment by dev-pro-alexander-subota** [comment]
Закрываю, открыл следующий issue #7
